[versions]
agp = "8.7.2"
androidxJunit = "1.1.3"
appcompatVersion = "1.4.0"
cameraxVersion = "1.2.0-alpha02"
espressoCoreVersion = "3.4.0"
kotlin = "1.9.0"
mapsSecret = "2.0.1"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
googlemaps = "19.0.0"
constraintlayout = "2.1.4"
googleGmsGoogleServices = "4.4.2"
firebaseAuth = "23.0.0"
gridlayout = "1.0.0"
navVersion = "2.5.3"
places = "4.0.0"
playServicesMaps = "18.1.0"
playSevicesMaps = "19.0.0"
navigationFragmentKtx = "2.8.3"
cameraCore = "1.3.4"
recyclerview = "1.3.2"
tasksVision = "0.20230731"
window = "1.3.0"

[libraries]
androidx-appcompat-v140 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraxVersion" }
androidx-camera-core-v120alpha02 = { module = "androidx.camera:camera-core", version.ref = "cameraxVersion" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraxVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraxVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v113 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-navigation-fragment-ktx-v253 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuth" }
gms-play-sevices-maps = { module = "com.google.android.gms:play-sevices-maps", version.ref = "playSevicesMaps" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
google-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "googlemaps" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
play-services-maps-v1810 = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
tasks-vision = { module = "com.google.mediapipe:tasks-vision", version.ref = "tasksVision" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
maps-secret = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "mapsSecret" }

